version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: ./backend
    environment:
      POSTGRES_URL: ""
      POSTGRES_USERNAME: ""
      POSTGRES_PASSWORD: ""
      AWS_ACCESS_KEY: ""
      AWS_SECRET_KEY: ""
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres-data:
