version: '3.9'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - 5432:5432
