spring:
    application:
        name: wuhu-server
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres?sslmode=disable
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres

aws:
    access_key_id: ${AWS_ACCESS_KEY}
    secret_access_key: ${AWS_SECRET_KEY}