spring:
    application:
        name: wuhu-server
    datasource:
        url: ${POSTGRES_URL}
        driverClassName: org.postgresql.Driver
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}

aws:
    access_key_id: ${AWS_ACCESS_KEY}
    secret_access_key: ${AWS_SECRET_KEY}